[package]
name = "audit-userspace-rs"
license = "MPL-2.0"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
chrono = "0.4"

[dependencies]
auparse-sys = { path = "auparse-sys" }

[workspace]
members = [
    "auparse-sys"
]
